// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'ar'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	title: {
		/**
		 * V​i​k​e​ ​V​u​e
		 */
		app_name: string
		/**
		 * V​i​k​e​ ​v​u​e​ ​t​e​m​p​l​a​t​e
		 */
		app_description: string
	}
	error: {
		/**
		 * 4​0​4​ ​P​a​g​e​ ​N​o​t​ ​F​o​u​n​d
		 */
		'404': string
		/**
		 * 5​0​0​ ​I​n​t​e​r​n​a​l​ ​S​e​r​v​e​r​ ​E​r​r​o​r
		 */
		'500': string
		/**
		 * S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g​.
		 */
		went_wrong: string
		/**
		 * T​h​i​s​ ​p​a​g​e​ ​c​o​u​l​d​ ​n​o​t​ ​b​e​ ​f​o​u​n​d​.
		 */
		not_found: string
	}
	/**
	 * H​i​ ​t​h​e​r​e​!​ ​W​e​l​c​o​m​e​ ​t​o​ ​V​i​k​e​ ​V​u​e​!
	 */
	HI: string
}

export type TranslationFunctions = {
	title: {
		/**
		 * Vike Vue
		 */
		app_name: () => LocalizedString
		/**
		 * Vike vue template
		 */
		app_description: () => LocalizedString
	}
	error: {
		/**
		 * 404 Page Not Found
		 */
		'404': () => LocalizedString
		/**
		 * 500 Internal Server Error
		 */
		'500': () => LocalizedString
		/**
		 * Something went wrong.
		 */
		went_wrong: () => LocalizedString
		/**
		 * This page could not be found.
		 */
		not_found: () => LocalizedString
	}
	/**
	 * Hi there! Welcome to Vike Vue!
	 */
	HI: () => LocalizedString
}

export type Formatters = {}
